<?php

/**
 * Split de paiement landing -- markup transcribed verbatim from the design
 * mockup body (see .exploration-landings.md), served through
 * theme_page_templates + template_include (inc/templates.php).
 *
 * @package UnlockerLandings
 */

namespace Unlocker\Landings;

?><!doctype html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width,initial-scale=1">
<?php wp_head(); ?>
</head>
<body <?php body_class('ul-page-split'); ?>>
<?php wp_body_open(); ?><div class="ul-split-header"><header class="ul-header ul-container"><a href="<?php echo esc_url(home_url('/')); ?>"><img class="ul-logo" src="<?php echo esc_url(asset_url('logo-blanc.svg')); ?>" alt="Unlocker" width="168" height="25"></a><div class="ul-split-header-right"><span>Conciergeries de montagne</span><a data-ul-start class="ul-btn" href="<?php echo esc_url(demarrer_url('offre=split')); ?>">Démarrer avec le split</a></div></header></div><main id="ul-main"><section class="ul-split-hero ul-container"><div class="ul-split-copy"><p class="ul-eyebrow">Split de paiement · Conciergeries de montagne</p><h1>Le ménage de vos propriétaires ?<br><span>Ce n’est plus à vous de l’avancer.</span></h1><p class="ul-split-lead">Le split de paiement Unlocker répartit les encaissements de location saisonnière entre votre commission, les propriétaires et vos prestataires. Pour vos chalets et appartements en station, le ménage est payé sur les fonds reçus : moins d’attente des virements propriétaires, plus de disponibilité pour les arrivées en haute saison.</p><div class="ul-actions"><a data-ul-start class="ul-btn" href="<?php echo esc_url(demarrer_url('offre=split')); ?>">Démarrer avec le split</a><a data-ul-start class="ul-link" href="<?php echo esc_url(demarrer_url('offre=split&parcours=demo')); ?>">Réserver une démo</a></div><p class="ul-split-caption">Ménage, linge, maintenance : vos prestataires aussi ont leur part.</p></div><div class="ul-split-visual"><img class="ul-split-photo" src="<?php echo esc_url(asset_url('images/split-scene-768.webp')); ?>" srcset="<?php echo esc_url(asset_url('images/split-scene-768.webp')); ?> 768w, <?php echo esc_url(asset_url('images/split-scene-1536.webp')); ?> 1536w" sizes="(max-width: 760px) 100vw, 50vw" alt="Chalet éclairé au pied des montagnes enneigées" width="1536" height="1024" fetchpriority="high"><div class="ul-split-example"><div class="ul-split-example-head"><span>Encaissement du séjour</span><strong>2 840 €</strong></div><div class="ul-flow-bar" aria-hidden="true"><i></i><i></i><i></i></div><div class="ul-flow-row"><span><i class="ul-dot"></i>Propriétaire</span><strong>1 750 €</strong></div><div class="ul-flow-row"><span><i class="ul-dot ul-dot--pink"></i>Votre conciergerie</span><strong>710 €</strong></div><div class="ul-flow-row"><span><i class="ul-dot ul-dot--gray"></i>Ménage</span><strong>380 €</strong></div><p class="ul-fine">Exemple illustratif de répartition, et non un tarif.</p></div></div></section>
<section class="ul-section ul-split-dark"><div class="ul-container"><div class="ul-split-heading-right"><p class="ul-kicker">Quand la station fait le plein</p><h2>Les arrivées s’enchaînent.<br><span>Les paiements suivent.</span></h2></div><div class="ul-split-benefits"><article><span class="ul-split-metric">0 €</span><h3>Aucune avance de trésorerie</h3><p>Les prestations prévues sont réglées sur les fonds du séjour encaissés. Votre conciergerie garde sa trésorerie pour son activité.</p></article><article><span class="ul-split-metric">0j</span><h3>Pas de retard, pas de relance</h3><p>Plus besoin d’attendre un virement du propriétaire : la répartition suit les règles définies, à partir des fonds reçus.</p></article><article><span class="ul-split-metric">0</span><h3>Frustration</h3><p>Votre commission, les prestations et la part du propriétaire sont visibles. Chacun sait ce qui lui revient, avec moins d’incompréhensions.</p></article></div><p class="ul-fine ul-split-metric-note">Le split agit sur les fonds reçus ; les délais bancaires restent applicables.</p></div></section>
<section class="ul-section"><div class="ul-container"><p class="ul-kicker">Le split, concrètement</p><div class="ul-split-section-head"><h2>Le split de paiement,<br>comment ça marche ?</h2><p>Le split de paiement est la répartition automatique d’un encaissement entre plusieurs bénéficiaires. Pour une conciergerie de location saisonnière, Unlocker applique les règles prévues pour le propriétaire, la commission et les prestataires.</p></div><ol class="ul-split-timeline" role="list"><li><span class="ul-split-timeline-marker" aria-hidden="true">01</span><div><h3>Un IBAN pour le logement</h3><p>Le bien dispose de coordonnées bancaires dédiées chez Unlocker.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">02</span><div><h3>Le séjour est encaissé</h3><p>Les plateformes de réservation, comme Airbnb ou Booking, versent les fonds sur l’IBAN du logement.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">03</span><div><h3>Vos règles s’appliquent</h3><p>La commission et les prestations déterminent les parts à répartir.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">04</span><div><h3>Chacun reçoit sa part</h3><p>Propriétaire, conciergerie et prestataires sont payés depuis cet encaissement.</p></div></li></ol><p class="ul-split-worked-example">Exemple : sur 2 840 € encaissés, 1 750 € reviennent au propriétaire, 710 € à la conciergerie et 380 € au prestataire de ménage. Montants illustratifs, selon les règles choisies.</p></div></section>
<section class="ul-split-owner"><div class="ul-container ul-grid"><div class="ul-split-provider-heading"><p class="ul-kicker">Le paiement des prestataires</p><h2>Payez vos prestataires.<br>Sans attendre vos propriétaires.</h2></div><div><p>Les frais de ménage en location saisonnière, le linge et la maintenance peuvent entrer dans vos règles de répartition. Le paiement des prestataires s’appuie sur les fonds du séjour reçus, pour préserver la trésorerie de votre conciergerie.</p><p>Vous évitez de verser toute la somme au propriétaire, puis d’attendre son règlement : moins de délais et de relances entre deux séjours. Il conserve la visibilité sur les encaissements et les parts distribuées depuis son espace dédié.</p></div></div></section>
<section class="ul-section ul-split-delegation"><div class="ul-container ul-grid"><div><p class="ul-kicker">Conformité &amp; délégation Carte G</p><h2>Délégation Carte G :<br>un cadre pour votre conciergerie.</h2></div><div><p>Le split répartit les paiements ; la délégation Carte G Unlocker définit les missions confiées et les responsabilités de chacun. Ce sont deux fonctions distinctes. Vous gardez la main sur le terrain et la relation avec vos propriétaires, dans le périmètre prévu par votre délégation.</p><p class="ul-fine">Le périmètre est défini dans votre contrat de délégation.</p><a class="ul-btn ul-btn--outline" href="<?php echo esc_url(delegation_url()); ?>">Voir la délégation Carte G</a></div></div></section>
<section class="ul-section ul-split-setup"><div class="ul-container"><div class="ul-split-heading-right"><p class="ul-kicker">Pour votre prochain séjour</p><h2>Activez le split pour<br>votre premier logement.</h2></div><ol class="ul-split-timeline ul-split-timeline--setup" role="list"><li><span class="ul-split-timeline-marker" aria-hidden="true">01</span><div><h3>Créez votre compte</h3><p>Présentez votre conciergerie et choisissez votre offre.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">02</span><div><h3>Configurez vos propriétaires et prestataires</h3><p>Renseignez les bénéficiaires et leurs informations pour préparer la répartition des paiements.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">03</span><div><h3>Préparez le logement</h3><p>Ajoutez le bien et définissez les règles de répartition de ses encaissements.</p></div></li><li><span class="ul-split-timeline-marker" aria-hidden="true">04</span><div><h3>Percevez vos frais</h3><p>Votre commission est versée selon les règles définies, à partir des fonds du séjour encaissés.</p></div></li></ol></div></section><section class="ul-close ul-split-close-right"><div class="ul-container"><div class="ul-split-heading-right"><p class="ul-kicker">Le split Unlocker</p><h2>Gardez votre énergie pour la saison.<br><span>Automatisez vos répartitions.</span></h2></div><div class="ul-actions"><a data-ul-start class="ul-btn" href="<?php echo esc_url(demarrer_url('offre=split')); ?>">Démarrer avec le split</a><a data-ul-start class="ul-link" href="<?php echo esc_url(demarrer_url('offre=split&parcours=demo')); ?>">Réserver une démo</a></div></div></section><section class="ul-section"><div class="ul-container ul-faq"><h2>Split de paiement : vos questions</h2><?php render_faq(TEMPLATE_SPLIT); ?></div></section></main><footer class="ul-footer"><div class="ul-container"><img class="ul-logo" src="<?php echo esc_url(asset_url('logo.svg')); ?>" alt="Unlocker" width="124" height="20"><div class="ul-footer-links"><span>© Unlocker</span><a href="https://unlocker.io/politique-de-confidentialite/">Confidentialité</a><a href="https://unlocker.io/mentions-legales/">Mentions légales</a><a href="mailto:contact@unlocker.io">Contacter Unlocker</a></div></div></footer>
<?php wp_footer(); ?>
</body>
</html>
